### ISSUE TITLE
缺少Model包

### ISSUE THREAD

**Issue by YxYL6125** [WackyGem/Nicol#1]
import org.example.nicol.domain.system.model

但是domain.system下没有model包

**Comment by WackyGem** [comment]
In an unforeseen mistake, I excluded the model folder in my [.gitignore](https://github.com/WackyGem/Nicol/blob/348e14c4149048c95ca5406cf06e0d3935d746d1/.gitignore#L6C1-L8) file,

which is used to store local models, and accidentally excluded the model package as well.

I will fix it right now.

**Comment by WackyGem** [comment]
Hi~ @YxYL6125  ,  Thank you so much for being able to point this out.

I've uploaded additional class files that were overlooked. 

This issue will be closed soon.

**Comment by YxYL6125** [comment]
> In an unforeseen mistake, I excluded the model folder in my [.gitignore](https://github.com/WackyGem/Nicol/blob/348e14c4149048c95ca5406cf06e0d3935d746d1/.gitignore#L6C1-L8) file,
> 
> 好像还有一些包/文件没有上传完全。例如一些扩展方法；类：

![image-20231030083637141](https://raw.githubusercontent.com/YxYL6125/imgBad/main/img/image-20231030083637141.png)

![image-20231030083648821](https://raw.githubusercontent.com/YxYL6125/imgBad/main/img/image-20231030083648821.png)

![image-20231030083704750](https://raw.githubusercontent.com/YxYL6125/imgBad/main/img/image-20231030083704750.png)

![image-20231030083720458](https://raw.githubusercontent.com/YxYL6125/imgBad/main/img/image-20231030083720458.png)

我一共排查到的就这5个类

**Comment by WackyGem** [comment]
> > In an unforeseen mistake, I excluded the model folder in my [.gitignore](https://github.com/WackyGem/Nicol/blob/348e14c4149048c95ca5406cf06e0d3935d746d1/.gitignore#L6C1-L8) file,
> > 好像还有一些包/文件没有上传完全。例如一些扩展方法；类：
> 
> ![image-20231030083637141](https://raw.githubusercontent.com/YxYL6125/imgBad/main/img/image-20231030083637141.png)
> 
> ![image-20231030083648821](https://raw.githubusercontent.com/YxYL6125/imgBad/main/img/image-20231030083648821.png)
> 
> ![image-20231030083704750](https://raw.githubusercontent.com/YxYL6125/imgBad/main/img/image-20231030083704750.png)
> 
> ![image-20231030083720458](https://raw.githubusercontent.com/YxYL6125/imgBad/main/img/image-20231030083720458.png)
> 
> 我一共排查到的就这5个类

Hi ～ ,  @YxYL6125  ,  Thank you very much for your feedback once again, but this is a feature of the framework rather than a missing file.  

For more details, please refer to Jimmer's documentation regarding [the automatic generation of this code using KSP](https://babyfish-ct.gitee.io/jimmer-doc/docs/overview/get-started/generate-code?_highlight=%E7%94%9F%E6%88%90#%E4%BB%A3%E7%A0%81%E7%94%9F%E6%88%90) .

If you want to run this project from the source code, please use Gradle for compilation.  like `gradle build` .

Then you will see that the missing code will be generated in the "build" folder located in the root directory of the current project.
